[phases.setup]
nixPkgs = ["dotnet-sdk_8", "dotnet-runtime_8"]

[phases.install]
cmds = ["cd Estacionamento.Api && dotnet restore"]

[phases.build]
cmds = ["cd Estacionamento.Api && dotnet publish -c Release -o ./publish --self-contained false"]

[start]
cmd = "cd Estacionamento.Api/publish && dotnet Estacionamento.Api.dll"

