[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu"]

[phases.install]
cmds = ["cd Estacionamento.Api && dotnet restore"]

[phases.build]
cmds = ["cd Estacionamento.Api && dotnet publish -c Release -o ./publish --self-contained true -r linux-x64"]

[start]
cmd = "cd Estacionamento.Api/publish && ./Estacionamento.Api"

